# -*- coding: utf-8 -*-
"""AAPL1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11WrONbLo-QYzGQGMc4LeKkNSo9shh_1u
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

df = pd.read_excel('AAPL.xlsx')
df.info()

df.head(11)

df.describe()

df = df.drop_duplicates()

df['Date'] = pd.to_datetime(df['Date'])

df.isnull().sum()