# -*- coding: utf-8 -*-
"""Week4_IIBCA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E6NzQAXl5hdsbonBPsuZARqIBqC53BIe

**Shopify Stock Visualization, Time-Series Analysis & Financial Insights**

Build line plots for OHLC prices and trading volumes over time.

Plot 20-day and 50-day moving averages alongside daily closing prices.

Generate histogram and KDE plots for daily returns to check for normal vs. fat-tailed distributions.

Produce a financial summary report detailing stock stability and high-volatility periods.
"""

#Build line plots for OHLC prices and trading volumes
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("shopify_stock.csv")

df.head()

df.columns

df.dtypes

df["date"] = pd.to_datetime(df["date"],utc=True)
df['date'].dtype

df = df.sort_values("date")

df["Date"] = pd.to_datetime(df["date"],utc=True)
df

#OHLC
plt.figure(figsize=(16, 8))

plt.plot(df.index, df["open"], label="open")
plt.plot(df.index, df["high"], label="high")
plt.plot(df.index, df["low"], label="low")
plt.plot(df.index, df["close"], label="close")

plt.title("Shopify Stock OHLC Prices")
plt.xlabel("Date")
plt.ylabel("Price")
plt.legend()
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(16,8))

plt.plot(df["date"],df["volume"])
plt.title("Shopify volume analysis")
plt.xlabel("Date")
plt.ylabel("Volume of trade shares")
plt.show()

df["MA20"] = df["close"].rolling(window=20).mean()

df["MA50"] = df["close"].rolling(window=50).mean()

plt.figure(figsize=(12, 6))

plt.plot(df.index, df["close"], label="Daily Close")
plt.title("Shopify Stock closing price trend")
plt.xlabel("Date")
plt.ylabel("Price")
plt.legend()
plt.xticks(rotation=45)
plt.show()

#Moving Average
plt.figure(figsize=(12, 6))

plt.plot(df['date'], df["MA20"], label="20-Day MA")

plt.title("Shopify Stock Price Moving Averages for short term")
plt.xlabel("Date")
plt.ylabel("Price")
plt.legend()
plt.xticks(rotation=45)
plt.show()

#Moving Average
plt.figure(figsize=(12, 6))

plt.plot(df['date'], df["MA50"], label="50-Day MA")

plt.title("Shopify Stock Price Moving Averages for long term")
plt.xlabel("Date")
plt.ylabel("Price")
plt.legend()
plt.xticks(rotation=45)
plt.show()

#Moving Average
plt.figure(figsize=(12, 6))

plt.plot(df.index, df["close"], label="Daily Close")
plt.plot(df.index, df["MA20"], label="20-Day MA")
plt.plot(df.index, df["MA50"], label="50-Day MA")

plt.title("Shopify Stock Price and Moving Averages")
plt.xlabel("Date")
plt.ylabel("Price")
plt.legend()
plt.xticks(rotation=45)
plt.show()

#Daily return
df["Daily_Return"] = df["close"].pct_change()


df

plt.figure(figsize=(10, 6))

sns.histplot(
    df["Daily_Return"].dropna(),
    bins=50,
    kde=True
)

plt.title("Shopify Daily Returns")
plt.xlabel("Daily Return")
plt.ylabel("Frequency")
plt.show()

#Rolling Volatility
df["Rolling_Volatility_20"] = (
    df["Daily_Return"]
    .rolling(window=20)
    .std()
)
df["Rolling_Volatility_20"].dropna()

plt.figure(figsize=(12, 6))

plt.plot(
    df.index,
    df["Rolling_Volatility_20"]
)

plt.title("Shopify 20-Day Rolling Volatility")
plt.xlabel("Date")
plt.ylabel("Volatility")
plt.xticks(rotation=45)
plt.show()

