# -*- coding: utf-8 -*-
"""STUDENT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1szPOT5LTpPuwSzShKGV-238lVIxRGWOp
"""

import pandas as pd
import numpy as np

df = pd.read_csv("StudentsPerformance.csv")

df.head()

df.dtypes

df.info()

df.isnull().sum()

df.tail()

df.describe()

df.columns

categorical_cols = {
    "gender",
    "race/ethnicity",
    "parental level of education",
    "lunch",
    "test preparation course"
}

for col in categorical_cols:
  df[col] = df[col].str.strip().str.title()
print(df[list(categorical_cols)].head())
df['average_score'] = (
    df['math score'] +
    df['reading score'] +
    df['writing score']
) / 3
df['total_score'] = (
    df['math score'] +
    df['reading score'] +
    df['writing score']
)