# -*- coding: utf-8 -*-
"""HEALTHCARE 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HPb7283nlz3fRXYXH0T3SgZ5tfsd2mW-
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("healthcare_dataset.csv")

df.head(10)

df.tail(20)

df.dtypes

df.columns

df.info

df.isnull().sum()

df['Billing Amount'].describe()

df['Discharge Date'] = pd.to_datetime(df['Discharge Date'])
df['Date of Admission'] = pd.to_datetime(df['Date of Admission'])
df['Stay_Days'] = (df['Discharge Date'] - df['Date of Admission']).dt.days
df['Stay_Days']

df['Stay_Days'] = (df['Discharge Date'] - df['Date of Admission']).dt.days
df['Stay_Days']

df['Discharge Date'] = pd.to_datetime(df['Discharge Date'])
df['Date of Admission'] = pd.to_datetime(df['Date of Admission'])
df['Stay_Days']=(df['Discharge Date']-df['Date of Admission']).dt.days
df['Stay_Days']