# -*- coding: utf-8 -*-
"""AAPL 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZV4gVqrdKdcYxFXcuplkOZBbURI1yyLo
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_excel('/content/AAPL (2).xlsx')

df.head()

df.columns

df.dtypes

plt.figure(figsize=(16, 8))
plt.plot(df.index, df["Open"], label="Open")
plt.plot(df.index, df["High"], label="High")
plt.plot(df.index, df["Low"], label="Low")
plt.plot(df.index, df["Close"], label="Close")
plt.title(" Stock OHLC Prices")
plt.xlabel("Date")
plt.ylabel("Price")
plt.legend()
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(12, 5))

plt.plot(df["Date"], df["Volume"])

plt.title("AAPL Trading Volume Over Time")
plt.xlabel("Date")
plt.ylabel("Trading Volume")


plt.show()

plt.figure(figsize=(12, 6))
plt.plot(df['Date'], df['Close'], label="Close Price")
plt.title(" Moving Averages for short term")
plt.xlabel("Date")
plt.ylabel("Price")
plt.legend()
plt.xticks(rotation=45)
plt.show()

df["Daily_Return"] = df["Close"].pct_change()

plt.figure(figsize=(10, 6))
plt.hist(df["Daily_Return"].dropna(), bins=50)
plt.title("Histogram of Daily Returns")
plt.xlabel("Daily Return")
plt.ylabel("Frequency")
plt.show()

